### ISSUE TITLE
cant use bincheck and freebin 

### ISSUE THREAD

**Issue by erwinwahyura** [kecci/go-bin#3]
seems the release missing something?
its should be folder structure Bincheck and Freebin there.
<img width="241" alt="Screen Shot 2022-08-03 at 11 51 42" src="https://user-images.githubusercontent.com/23116619/182526766-ad7a6846-5ca7-468d-baa2-e35fe8cb6a17.png">

**Comment by kecci** [comment]
I check on the tree, the folder is already on it. Please check this tree: https://github.com/kecci/go-bin/tree/v0.0.2

You can try to 
1. Remove the vendor folder
2. Clean up the go.sum related with go-bin
3. Update the go-mod to v0.0.2
4. Run `go get -u github.com/kecci/go-bin` to update the mod / pkg

<img width="1051" alt="Screen Shot 2022-08-03 at 11 53 36" src="https://user-images.githubusercontent.com/25241073/182526951-23af79c9-2829-4769-b877-60810ac541b9.png">

**Comment by erwinwahyura** [comment]
resolved. thanks
